### ISSUE TITLE
Diff. between pub and emitter?

### ISSUE THREAD

**Issue by KrishnaPG** [mcollina/mqemitter#4]
Trying to understand this emitter concept. 

So, what is its scope and where is it used? In the code example on ReadMe, the emitter object is created without specifying any broker or other pub/sub.

So, where does this fit in the whole `pub -> MQTT Broker -> sub` pipeline / scenario?

**Comment by RangerMauve** [comment]
As I understand it, mqemitter doesn't actually connect to any broker. It's like a regular EventEmitter, but it accepts the same wildcards that MQTT does in the event names.

**Comment by mcollina** [comment]
Also it fully respect backpressure.

It also has mongo https://github.com/mcollina/mqemitter-mongodb and https://github.com/mcollina/mqemitter-redis support

**Comment by KrishnaPG** [comment]
Thank you @RangerMauve and @mcollina .

I am trying to come-up with some good use case to utilize this, but falling short of few things.

For example, the example code is creating an `emitter object`, which means it is scoped to its file or module and hence not distributed across machines (like, say MQTT pub/sub). Or is it?
    1. If it *can* work in distributed mode, then I am wondering what is difference between MQTT pub/sub and this? 
    2. If it *cannot* work in distributed mode, then the role of `mongodb` and `redis` is not clear. Can someone consume events from those `redis` and `mongodb` backends or is it more like persistent storage just to handle the backlog?

**Comment by mcollina** [comment]
This is an eventemitter-like object that _supports backpressure_, so that you can know when a specific event has been fully processed. There are good usage for this scenario, basically when you are working with real-time apps and events (in this way a single client cannot crush your process).
The Redis and MongoDB ones are for distributed support.

Regarding your question: MQTT is a device-to-cloud thing, not a server to server one. Also, MQTT is a protocol, and this is just an API :).
